---
title: "MultiSV Figure"
author: "Xinmeng Liao"
date: "2025-06-13"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
library(data.table)
library(clusterProfiler)
library(org.Hs.eg.db)
library(ggsci)
library(viridis)
for (i in c("select","filter", "mutate","rename", "left_join", "slice")){
  conflicted::conflict_prefer(i, "dplyr")
}
rm(i)
conflicted::conflicts_prefer(stats::sd)
conflicted::conflicts_prefer(httr::content)
conflicted::conflicts_prefer(plotly::layout)
```

# 1. Load files 
```{r}
result_file <- "/Users/xinmengliao/Documents/Project/20250516_Webserver/usr_output/output_cnv.tsv"
result <- read.csv(result_file,header = T,sep = "\t")
output_file <- "/Users/xinmengliao/Documents/Project/20250516_Webserver/usr_output/Variant/MultiSV/multisv_output.txt"
```

# Erichment analysis 
```{r}
gene_list <- result$Gene_name %>% unique()
gene_list <- unlist(strsplit(split = ";",gene_list)) %>% unique()
gene_df <- bitr(gene_list, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)

# GO-CC
if (nrow(gene_df) > 0) {
  enrich_res_gocc <- enrichGO(gene = gene_df$ENTREZID,
                              OrgDb = org.Hs.eg.db,
                              ont = "CC",
                              pAdjustMethod = "BH",
                              pvalueCutoff = 1,
                              readable = TRUE) %>% 
    as.data.frame() %>% mutate(Source  = " GO-CC")
}else{
  enrich_res_gocc <- data.frame()
}

if(nrow(enrich_res_gocc) > 0 ){
  if(nrow(enrich_res_gocc)>= 10 ){
  gocc_plot <- enrich_res_gocc %>% arrange(p.adjust) %>% slice(1:10)
  }else if(nrow(enrich_res_gocc) < 10 ){
    gocc_plot <- enrich_res_gocc %>% arrange(p.adjust)
  }
  
  gocc_plot$Description <- gsub("_", " ", gocc_plot$Description)
  gocc_plot$Description <- factor(gocc_plot$Description, levels = rev(gocc_plot$Description))
  gocc_plot$significance <- -log10(gocc_plot$p.adjust)
  res_num <- nrow(gocc_plot)
  
  gocc_plot.p <- ggplot(gocc_plot, aes(x = significance, y = Description, color = round(p.adjust, 2))) +
      geom_point(size = 3) +
      scale_color_gradient(low = "red", high = "blue") +
      labs(x = "-log10(p.adj)", y = "", color = "p.adj", size = "Gene count", title = paste("Top ", res_num, " enriched GO-CC terms")) +
      theme_classic() +
      theme(
        axis.text.y = element_text(size = 11),
        legend.position = "right")
  ggsave(gocc_plot.p, filename = gsub("txt","gocc_plot.png",output_file),dpi = 300)
}
  

# GO-BP
if (nrow(gene_df) > 0) {
  enrich_res_gobp <- enrichGO(gene = gene_df$ENTREZID,
                              OrgDb = org.Hs.eg.db,
                              ont = "BP",
                              pAdjustMethod = "BH",
                              pvalueCutoff = 1,
                              readable = TRUE) %>% 
    as.data.frame() %>% mutate(Source  = " GO-BP")
}else{
  enrich_res_gobp <- data.frame()
}

if(nrow(enrich_res_gobp) > 0 ){
  if(nrow(enrich_res_gobp)>= 10 ){
  gobp_plot <- enrich_res_gobp %>% arrange(p.adjust) %>% slice(1:10)
  }else if(nrow(enrich_res_gobp) < 10 ){
    gobp_plot <- enrich_res_gobp %>% arrange(p.adjust)
  }
  
  gobp_plot$Description <- gsub("_", " ", gobp_plot$Description)
  gobp_plot$Description <- factor(gobp_plot$Description, levels = rev(gobp_plot$Description))
  gobp_plot$significance <- -log10(gobp_plot$p.adjust)
  res_num <- nrow(gobp_plot)
  
  gobp_plot.p <- ggplot(gobp_plot, aes(x = significance, y = Description, color = round(p.adjust, 2))) +
      geom_point(size = 3) +
      scale_color_gradient(low = "red", high = "blue") +
      labs(x = "-log10(p.adj)", y = "", color = "p.adj", size = "Gene count", title = paste("Top ", res_num, " enriched GO-BP terms")) +
      theme_classic() +
      theme(
        axis.text.y = element_text(size = 11),
        legend.position = "right")
  ggsave(gobp_plot.p, filename = gsub("txt","gobp_plot.png",output_file),dpi = 300)
}
  
# GO-MF
if (nrow(gene_df) > 0) {
  enrich_res_gomf <- enrichGO(gene = gene_df$ENTREZID,
                              OrgDb = org.Hs.eg.db,
                              ont = "MF",
                              pAdjustMethod = "BH",
                              pvalueCutoff = 1,
                              readable = TRUE) %>% 
    as.data.frame() %>% mutate(Source  = " GO-MF")
}else{
  enrich_res_gomf <- data.frame()
}

if(nrow(enrich_res_gomf) > 0 ){
  if(nrow(enrich_res_gomf)>= 10 ){
  gomf_plot <- enrich_res_gomf %>% arrange(p.adjust) %>% slice(1:10)
  }else if(nrow(enrich_res_gomf) < 10 ){
    gomf_plot <- enrich_res_gomf %>% arrange(p.adjust)
  }
  
  gomf_plot$Description <- gsub("_", " ", gomf_plot$Description)
  gomf_plot$Description <- factor(gomf_plot$Description, levels = rev(gomf_plot$Description))
  gomf_plot$significance <- -log10(gomf_plot$p.adjust)
  res_num <- nrow(gomf_plot)
  
  gomf_plot.p <- ggplot(gomf_plot, aes(x = significance, y = Description, color = round(p.adjust, 2))) +
      geom_point(size = 3) +
      scale_color_gradient(low = "red", high = "blue") +
      labs(x = "-log10(p.adj)", y = "", color = "p.adj", size = "Gene count", title = paste("Top ", res_num, " enriched GO-MF terms")) +
      theme_classic() +
      theme(
        axis.text.y = element_text(size = 11),
        legend.position = "right")
  ggsave(gomf_plot.p, filename = gsub("txt","gomf_plot.png",output_file),dpi = 300)
}

# KEGG
if (nrow(gene_df) > 0) {
  enrich_res_kegg <- enrichKEGG(gene = gene_df$ENTREZID,
                              organism = "hsa",
                              keyType = "ncbi-geneid",
                              pAdjustMethod = "BH",
                              minGSSize = 1,
                              pvalueCutoff = 1) %>%  
    as.data.frame() %>% mutate(Source  = "KEGG")
}else{
  enrich_res_kegg <- data.frame()
}

if(nrow(enrich_res_kegg) > 0 ){
  if(nrow(enrich_res_kegg)>= 10 ){
  kegg_plot <- enrich_res_kegg %>% arrange(p.adjust) %>% slice(1:10)
  }else if(nrow(enrich_res_kegg) < 10 ){
    kegg_plot <- enrich_res_kegg %>% arrange(p.adjust)
  }
  
  kegg_plot$Description <- gsub("_", " ", kegg_plot$Description)
  kegg_plot$Description <- factor(kegg_plot$Description, levels = rev(gomf_plot$Description))
  kegg_plot$significance <- -log10(kegg_plot$p.adjust)
  res_num <- nrow(kegg_plot)
  
  if(unique(!is.na(kegg_plot$Description))){
    kegg_plot.p <- ggplot(kegg_plot, aes(x = significance, y = Description, color = round(p.adjust, 2))) +
      geom_point(size = 3) +
      scale_color_gradient(low = "red", high = "blue") +
      labs(x = "-log10(p.adj)", y = "", color = "p.adj", size = "Gene count", title = paste("Top ", res_num, " enriched GO-CC terms")) +
      theme_classic() +
      theme(
        axis.text.y = element_text(size = 11),
        legend.position = "right")
      ggsave(kegg_plot.p, filename = gsub("txt","kegg_plot.png",output_file),dpi = 300)
  }
  
}

enrich.all <- rbind(enrich_res_gocc, enrich_res_gobp, enrich_res_gomf, enrich_res_kegg %>% select(-category,-subcategory))
write.table(enrich.all, gsub("txt","enrichment.txt", output_file),quote = F,sep = "\t",row.names = F)

```

